name: C/C++ CI

on:
  push:
    branches: [ "branchHTTPsever" ]
  pull_request:
    branches: [ "branchHTTPsever" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4   
      
    - name: Configure
      run: ./configure  # Running the configure script

    - name: Build
      run: make  # Running make to build the project
